config/routes.rb
Rails.application.routes.draw do
  resources :holas

   root 'holas#index'

end

app/models/hola.rb
class Hola < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/holas_controller.rb
class HolasController < ApplicationController
  before_action :set_hola, only: [:show, :edit, :update, :destroy]

  # GET /holas
  # GET /holas.json
  def index
    @holas = Hola.all
  end

  # GET /holas/1
  # GET /holas/1.json
  def show
  end

  # GET /holas/new
  def new
    @hola = Hola.new
  end

  # GET /holas/1/edit
  def edit
  end

  # POST /holas
  # POST /holas.json
  def create
    @hola = Hola.new(hola_params)

    respond_to do |format|
      if @hola.save
        format.html { redirect_to @hola, notice: 'Hola was successfully created.' }
        format.json { render :show, status: :created, location: @hola }
      else
        format.html { render :new }
        format.json { render json: @hola.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holas/1
  # PATCH/PUT /holas/1.json
  def update
    respond_to do |format|
      if @hola.update(hola_params)
        format.html { redirect_to @hola, notice: 'Hola was successfully updated.' }
        format.json { render :show, status: :ok, location: @hola }
      else
        format.html { render :edit }
        format.json { render json: @hola.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holas/1
  # DELETE /holas/1.json
  def destroy
    @hola.destroy
    respond_to do |format|
      format.html { redirect_to holas_url, notice: 'Hola was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hola
      @hola = Hola.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hola_params
      params.require(:hola).permit(:texto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/holas_helper.rb
module HolasHelper
end

app/views/holas/_form.html.erb
<%= form_for(@hola) do |f| %>
  <% if @hola.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hola.errors.count, "error") %> prohibited this hola from being saved:</h2>

      <ul>
      <% @hola.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :texto %><br>
    <%= f.text_field :texto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/holas/edit.html.erb
<h1>Editing Hola</h1>

<%= render 'form' %>

<%= link_to 'Show', @hola %> |
<%= link_to 'Back', holas_path %>

app/views/holas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Holas</h1>

<table>
  <thead>
    <tr>
      <th>Texto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @holas.each do |hola| %>
      <tr>
        <td><%= hola.texto %></td>
        <td><%= link_to 'Show', hola %></td>
        <td><%= link_to 'Edit', edit_hola_path(hola) %></td>
        <td><%= link_to 'Destroy', hola, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hola', new_hola_path %>

app/views/holas/new.html.erb
<h1>New Hola</h1>

<%= render 'form' %>

<%= link_to 'Back', holas_path %>

app/views/holas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Texto:</strong>
  <%= @hola.texto %>
</p>

<%= link_to 'Edit', edit_hola_path(@hola) %> |
<%= link_to 'Back', holas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>